version: "2"
services:
  node1:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./oauth_server:/home/node/app
    ports:
      - "8888:8080"
    expose:
      - 8888
    command: "npm start"    
    
  
